name: CICD

on: 
  push: 
    branches: main


jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: |
          docker build \
          -t codehard04/tt-be \
          .
      - name: Publish image to docker hub
        run: docker push codehard04/tt-be:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps: 
      - name: Pull image from docker hub
        run: docker pull codehard04/tt-be:latest
      - name: Delete old container
        run: docker rm -f gaming-be-container
      - name: Run docker container
        run: >  
            docker run -d -p 7000:7000 \
            -e FE_URL=${{ secrets.FE_URL }} \
            -e JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
            -e PORT=${{ secrets.PORT }} \
            -e LINK_VERIFICATION=${{ secrets.LINK_VERIFICATION }} \
            -e PUBLICPATH=${{ secrets.PUBLICPATH }} \
            -e AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }} \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            -e AWS_REGION=${{ secrets.AWS_REGION }} \
            -e TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }} \
            -e TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }} \
            -e TWILIO_SERVICE_SID=${{ secrets.TWILIO_SERVICE_SID }} \
            -e TWILIO_PHONE_NUMBER=${{ secrets.TWILIO_PHONE_NUMBER }} \
            -e MAILER_EMAIL=${{ secrets.MAILER_EMAIL }} \
            -e MAILER_PASS=${{ secrets.MAILER_PASS }} \
            -e HOST=${{ secrets.HOST }} \
            -e USER=${{ secrets.USER }} \
            -e PASSWORD=${{ secrets.PASSWORD }} \
         --name gaming-be-container codehard04/tt-be:latest